In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
nltk.download("all")
import re
from sklearn.feature_extraction.text import *
from sklearn.metrics.pairwise import *

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\amith\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\amith\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\amith\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\amith\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\amith\AppData\Roaming\nltk_data...
[

In [38]:
list_of_stopwords = nltk.corpus.stopwords.words("english")

In [39]:
df = pd.read_csv("udemy_course_data.csv")
courses = df["course_title"].values

list_of_cleaned_courses = []

for i in courses:
    tokenised_words = nltk.tokenize.word_tokenize(i)
    p = []
    q = ""
    r = []
    for j in tokenised_words:
        p.append(nltk.stem.PorterStemmer().stem(j))
    for j in p:
        if j not in list_of_stopwords:
            q += (j + " ")
    q = q.strip()
    r = re.sub(r'[^a-zA-Z0-9\s]',"",q)
    list_of_cleaned_courses.append(r)

df_cleaned = df.copy()
df_cleaned["course_title_cleaned"] = list_of_cleaned_courses

In [40]:
def tokenise_my_course(my_course_name):
    tokenised_words = nltk.tokenize.word_tokenize(my_course_name)
    p = []
    q = ""
    r = []
    for j in tokenised_words:
        p.append(nltk.stem.PorterStemmer().stem(j))
    for j in p:
        if j not in list_of_stopwords:
            q += (j + " ")
    q = q.strip()
    r = re.sub(r'[^a-zA-Z0-9\s]',"",q)
    return r

In [41]:
df_cleaned.head()

course_id                                                 course_title  \
0    1070968                           Ultimate Investment Banking Course   
1    1113822  Complete GST Course & Certification - Grow Your CA Practice   
2    1006314     Financial Modeling for Business Analysts and Consultants   
3    1210588           Beginner to Pro - Financial Analysis in Excel 2017   
4    1011058                 How To Maximize Your Profits Trading Options   

                                                                               url  \
0                        https://www.udemy.com/ultimate-investment-banking-course/   
1                                    https://www.udemy.com/goods-and-services-tax/   
2  https://www.udemy.com/financial-modeling-for-business-analysts-and-consultants/   
3        https://www.udemy.com/complete-excel-finance-course-from-beginner-to-pro/   
4              https://www.udemy.com/how-to-maximize-your-profits-trading-options/   

   is_paid  price  num_subscribers  num_reviews  num_lectures  \
0     True    200             2147           23            51   
1     True     75             2792          923           274   
2     True     45             2174           74            51   
3     True     95             2451           11            36   
4     True    200             1276           45            26   

                level content_duration   published_timestamp  \
0          All Levels        1.5 hours  2017-01-18T20:58:58Z   
1          All Levels         39 hours  2017-03-09T16:34:20Z   
2  Intermediate Level        2.5 hours  2016-12-19T19:26:30Z   
3          All Levels          3 hours  2017-05-30T20:07:24Z   
4  Intermediate Level          2 hours  2016-12-13T14:57:18Z   

            subject  profit published_date published_time  year  month  day  \
0  Business Finance  429400     2017-01-18      20:58:58Z  2017      1   18   
1  Business Finance  209400     2017-03-09      16:34:20Z  2017      3    9   
2  Business Finance   97830     2016-12-19      19:26:30Z  2016     12   19   
3  Business Finance  232845     2017-05-30      20:07:24Z  2017      5   30   
4  Business Finance  255200     2016-12-13      14:57:18Z  2016     12   13   

                         course_title_cleaned  
0                     ultim invest bank cours  
1  complet gst cours  certif  grow ca practic  
2          financi model busi analyst consult  
3      beginn pro  financi analysi excel 2017  
4                   maxim profit trade option

In [42]:
my_course = "The Data Science Course"
tokenised_my_course = tokenise_my_course(my_course)

course_titles_cleaned = df_cleaned["course_title_cleaned"].values.tolist()
course_titles_cleaned = [tokenised_my_course] + course_titles_cleaned
course_titles_cleaned

['data scienc cours',
 'ultim invest bank cours',
 'complet gst cours  certif  grow ca practic',
 'financi model busi analyst consult',
 'beginn pro  financi analysi excel 2017',
 'maxim profit trade option',
 'trade penni stock  guid level 2017',
 'invest trade beginn  master price chart',
 'trade stock chart pattern immedi  explos gain',
 'option trade 3  advanc stock profit success method',
 'onli invest strategi need retir',
 'forex trade secret pro amazon s aw',
 'trade option money flow',
 'financi manag risk return secur',
 'forex trade cours  work smarter harder proven result',
 'python algo trade  sentiment trade new',
 'short sell  learn sell stock befor fall',
 'basic technic analysi  learn structur market',
 'complet chart pattern trade cours  proven approach',
 '7 deadli mistak invest slash profit ',
 'financi statement made easi',
 'win forex trade live forex trade exampl',
 'forex trader  creat first trade robot  code ',
 'creat busi home trade stock today 2017',
 'intro

In [43]:
tfidf = TfidfVectorizer()

vect = tfidf.fit_transform(course_titles_cleaned)

cos_sim = cosine_similarity(vect)
cos_sim

array([[1.        , 0.12369153, 0.07754146, ..., 0.        , 0.        ,
        0.        ],
       [0.12369153, 1.        , 0.08508524, ..., 0.        , 0.        ,
        0.        ],
       [0.07754146, 0.08508524, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.22549656],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.08831682],
       [0.        , 0.        , 0.        , ..., 0.22549656, 0.08831682,
        1.        ]])

In [21]:
similarity_matrix_values = []
similarity_matrix_indices = []
for i in cos_sim:
    cos = pd.Series(i)
    coz = cos.sort_values(ascending=False)
    pk = coz.index.values[1:]
    similarity_matrix_indices.append(pk)
    similarity_matrix_values.append(coz.values[1:])
similarity_matrix_values

[array([0.65363153, 0.57529378, 0.51569225, ..., 0.        , 0.        ,
        0.        ]),
 array([0.37371987, 0.36138497, 0.28739132, ..., 0.        , 0.        ,
        0.        ]),
 array([0.43814476, 0.41950695, 0.4140037 , ..., 0.        , 0.        ,
        0.        ]),
 array([0.5937185 , 0.59069808, 0.49286566, ..., 0.        , 0.        ,
        0.        ]),
 array([0.70537345, 0.5023693 , 0.48393211, ..., 0.        , 0.        ,
        0.        ]),
 array([0.60845638, 0.5719491 , 0.54685611, ..., 0.        , 0.        ,
        0.        ]),
 array([0.44768663, 0.41449124, 0.4042139 , ..., 0.        , 0.        ,
        0.        ]),
 array([0.49869762, 0.46313712, 0.40442689, ..., 0.        , 0.        ,
        0.        ]),
 array([0.49613637, 0.48279525, 0.46349673, ..., 0.        , 0.        ,
        0.        ]),
 array([0.39587348, 0.29423961, 0.26495983, ..., 0.        , 0.        ,
        0.        ]),
 array([0.40519991, 0.39297429, 0.36706731, ..., 0

In [44]:
df_cleaned["Similarity Indices"] = similarity_matrix_indices
df_cleaned["Similarity Values"] = similarity_matrix_values
df_cleaned.head()

course_id                                                 course_title  \
0    1070968                           Ultimate Investment Banking Course   
1    1113822  Complete GST Course & Certification - Grow Your CA Practice   
2    1006314     Financial Modeling for Business Analysts and Consultants   
3    1210588           Beginner to Pro - Financial Analysis in Excel 2017   
4    1011058                 How To Maximize Your Profits Trading Options   

                                                                               url  \
0                        https://www.udemy.com/ultimate-investment-banking-course/   
1                                    https://www.udemy.com/goods-and-services-tax/   
2  https://www.udemy.com/financial-modeling-for-business-analysts-and-consultants/   
3        https://www.udemy.com/complete-excel-finance-course-from-beginner-to-pro/   
4              https://www.udemy.com/how-to-maximize-your-profits-trading-options/   

   is_paid  price  num_subscribers  num_reviews  num_lectures  \
0     True    200             2147           23            51   
1     True     75             2792          923           274   
2     True     45             2174           74            51   
3     True     95             2451           11            36   
4     True    200             1276           45            26   

                level content_duration  ...           subject  profit  \
0          All Levels        1.5 hours  ...  Business Finance  429400   
1          All Levels         39 hours  ...  Business Finance  209400   
2  Intermediate Level        2.5 hours  ...  Business Finance   97830   
3          All Levels          3 hours  ...  Business Finance  232845   
4  Intermediate Level          2 hours  ...  Business Finance  255200   

   published_date published_time  year  month  day  \
0      2017-01-18      20:58:58Z  2017      1   18   
1      2017-03-09      16:34:20Z  2017      3    9   
2      2016-12-19      19:26:30Z  2016     12   19   
3      2017-05-30      20:07:24Z  2017      5   30   
4      2016-12-13      14:57:18Z  2016     12   13   

                         course_title_cleaned  \
0                     ultim invest bank cours   
1  complet gst cours  certif  grow ca practic   
2          financi model busi analyst consult   
3      beginn pro  financi analysi excel 2017   
4                   maxim profit trade option   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Similarity Indices  \
0                           [39, 242, 3479, 2719, 659, 419, 2807, 1215, 3008, 26, 1073, 420, 2648, 565, 229, 2505, 724, 139, 335, 2626, 3015, 3662, 1992, 3238, 172, 2708, 766, 173, 1849, 530, 364, 3529, 1006, 1216, 417, 466, 446, 992, 441, 127, 271, 538, 567, 892, 2645, 73, 177, 1152, 539, 87, 773, 775, 365, 105, 497, 338, 765, 2317, 805, 847, 1127, 3091, 1381, 2247, 378, 3056, 2912, 837, 2549, 2584, 2840, 1026, 171, 951, 711, 122, 1161, 457, 3510, 3467, 618, 166, 640, 3494, 559, 469, 2707, 866, 517, 728, 384, 2981, 61, 540, 3093, 203, 849, 2151, 796, 6, ...]   
1  [2491, 1044, 452, 2981, 554, 391, 397, 2524, 630, 1365, 1190, 761, 646, 443, 3009, 2600, 116, 927, 2515, 2601, 1001, 2819, 2514, 2717, 2646, 2743, 432, 3363, 3291, 2543, 519, 577, 806, 259, 264, 2312, 1613, 3237, 2905, 3261, 262, 409, 748, 1168, 166, 569, 726, 3213, 2043, 2519, 2979, 3566, 1964, 1745, 3316, 1409, 39, 1019, 2925, 3442, 980, 2557, 2721, 1628, 40, 98, 1991, 2493, 2741, 2616, 307, 3663, 2630, 2121, 2679, 34, 411, 32

In [45]:
course_name = "Ultimate Investment Banking Course"
def recommend_courses(course_name):
    movie_index = df_cleaned[df_cleaned["course_title"]==course_name].index[0]
    similar_indices = df_cleaned.loc[movie_index,"Similarity Indices"]
    top_5_movie_indices = similar_indices[0:5]
    df_top_5_movies = df_cleaned.loc[top_5_movie_indices,"course_title"].values
    return list(df_top_5_movies)
recommend_courses(course_name)

['The Complete Investment Banking Course 2017',
 'Advanced Accounting for Investment Banking',
 'The Ultimate jQuery Course',
 'The Ultimate Web Development Course',
 'Financial Accounting - The Ultimate Beginner Course']

In [27]:
"""
course_name = "Ultimate Investment Banking Course"
def recommend_courses_1(course_name):
    movie_index = df_cleaned[df_cleaned["course_title"]==course_name].index[0]
    similar_indices = df_cleaned.loc[movie_index,"Similarity Indices"]
    top_5_movie_indices = similar_indices[0:5]
    df_top_5_movies = df_cleaned.loc[top_5_movie_indices,:]
    return df_top_5_movies
recommend_courses_1(course_name)
"""
print("")