In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
nltk.download("all")
import re
from sklearn.feature_extraction.text import *
from sklearn.metrics.pairwise import *

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\amith\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\amith\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\amith\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\amith\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\amith\AppData\Roaming\nltk_data...
[

In [2]:
list_of_stopwords = nltk.corpus.stopwords.words("english")

In [3]:
def lemmatise(w):

    part_of_speech = nltk.pos_tag([w])[0][1].lower()

    if part_of_speech[0] == "n":
        pos = "n"
    elif part_of_speech[0] == "v":
        pos = "v"
    elif part_of_speech[0] == "j":
        pos = "adj"
    elif part_of_speech[0] == "r":
        pos = "adv"
    else:
        pos = part_of_speech

    return nltk.stem.WordNetLemmatizer().lemmatize(w, pos)

In [4]:
df = pd.read_csv("udemy_course_data.csv")
courses = df["course_title"].values

list_of_cleaned_courses = []

for i in courses:
    tokenised_words = nltk.tokenize.word_tokenize(i)
    p = []
    q = ""
    r = []
    for j in tokenised_words:
        p.append(nltk.stem.PorterStemmer().stem(j))
    for j in p:
        if j not in list_of_stopwords:
            q += (j + " ")
    q = q.strip()
    r = re.sub(r'[^a-zA-Z0-9\s]',"",q)
    list_of_cleaned_courses.append(r)

df_cleaned = df.copy()
df_cleaned["course_title_cleaned"] = list_of_cleaned_courses

In [5]:
tfidf = TfidfVectorizer()
vect = tfidf.fit_transform(df_cleaned["course_title_cleaned"])

cos_sim = cosine_similarity(vect)
cos_sim

array([[1.        , 0.08524937, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.08524937, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.22548828],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.08831355],
       [0.        , 0.        , 0.        , ..., 0.22548828, 0.08831355,
        1.        ]])

In [ ]:
df_cleaned["Similarity Indices"] = similarity_matrix_indices

In [43]:
similarity_matrix_values = []
similarity_matrix_indices = []
for i in cos_sim:
    cos = pd.Series(i)
    coz = cos.sort_values(ascending=False)
    pk = coz.index.values[1:]
    similarity_matrix_indices.append(pk)
    similarity_matrix_values.append(coz.values[1:])
similarity_matrix_values

[array([0.65363153, 0.57529378, 0.51569225, ..., 0.        , 0.        ,
        0.        ]),
 array([0.37371987, 0.36138497, 0.28739132, ..., 0.        , 0.        ,
        0.        ]),
 array([0.43814476, 0.41950695, 0.4140037 , ..., 0.        , 0.        ,
        0.        ]),
 array([0.5937185 , 0.59069808, 0.49286566, ..., 0.        , 0.        ,
        0.        ]),
 array([0.70537345, 0.5023693 , 0.48393211, ..., 0.        , 0.        ,
        0.        ]),
 array([0.60845638, 0.5719491 , 0.54685611, ..., 0.        , 0.        ,
        0.        ]),
 array([0.44768663, 0.41449124, 0.4042139 , ..., 0.        , 0.        ,
        0.        ]),
 array([0.49869762, 0.46313712, 0.40442689, ..., 0.        , 0.        ,
        0.        ]),
 array([0.49613637, 0.48279525, 0.46349673, ..., 0.        , 0.        ,
        0.        ]),
 array([0.39587348, 0.29423961, 0.26495983, ..., 0.        , 0.        ,
        0.        ]),
 array([0.40519991, 0.39297429, 0.36706731, ..., 0

In [44]:
df_cleaned["Similarity Indices"] = similarity_matrix_indices
df_cleaned["Similarity Values"] = similarity_matrix_values
df_cleaned.head()

course_id                                                 course_title  \
0    1070968                           Ultimate Investment Banking Course   
1    1113822  Complete GST Course & Certification - Grow Your CA Practice   
2    1006314     Financial Modeling for Business Analysts and Consultants   
3    1210588           Beginner to Pro - Financial Analysis in Excel 2017   
4    1011058                 How To Maximize Your Profits Trading Options   

                                                                               url  \
0                        https://www.udemy.com/ultimate-investment-banking-course/   
1                                    https://www.udemy.com/goods-and-services-tax/   
2  https://www.udemy.com/financial-modeling-for-business-analysts-and-consultants/   
3        https://www.udemy.com/complete-excel-finance-course-from-beginner-to-pro/   
4              https://www.udemy.com/how-to-maximize-your-profits-trading-options/   

   is_paid  price  num_subscribers  num_reviews  num_lectures  \
0     True    200             2147           23            51   
1     True     75             2792          923           274   
2     True     45             2174           74            51   
3     True     95             2451           11            36   
4     True    200             1276           45            26   

                level content_duration  ...           subject  profit  \
0          All Levels        1.5 hours  ...  Business Finance  429400   
1          All Levels         39 hours  ...  Business Finance  209400   
2  Intermediate Level        2.5 hours  ...  Business Finance   97830   
3          All Levels          3 hours  ...  Business Finance  232845   
4  Intermediate Level          2 hours  ...  Business Finance  255200   

   published_date published_time  year  month  day  \
0      2017-01-18      20:58:58Z  2017      1   18   
1      2017-03-09      16:34:20Z  2017      3    9   
2      2016-12-19      19:26:30Z  2016     12   19   
3      2017-05-30      20:07:24Z  2017      5   30   
4      2016-12-13      14:57:18Z  2016     12   13   

                         course_title_cleaned  \
0                     ultim invest bank cours   
1  complet gst cours  certif  grow ca practic   
2          financi model busi analyst consult   
3      beginn pro  financi analysi excel 2017   
4                   maxim profit trade option   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Similarity Indices  \
0                           [39, 242, 3479, 2719, 659, 419, 2807, 1215, 3008, 26, 1073, 420, 2648, 565, 229, 2505, 724, 139, 335, 2626, 3015, 3662, 1992, 3238, 172, 2708, 766, 173, 1849, 530, 364, 3529, 1006, 1216, 417, 466, 446, 992, 441, 127, 271, 538, 567, 892, 2645, 73, 177, 1152, 539, 87, 773, 775, 365, 105, 497, 338, 765, 2317, 805, 847, 1127, 3091, 1381, 2247, 378, 3056, 2912, 837, 2549, 2584, 2840, 1026, 171, 951, 711, 122, 1161, 457, 3510, 3467, 618, 166, 640, 3494, 559, 469, 2707, 866, 517, 728, 384, 2981, 61, 540, 3093, 203, 849, 2151, 796, 6, ...]   
1  [2491, 1044, 452, 2981, 554, 391, 397, 2524, 630, 1365, 1190, 761, 646, 443, 3009, 2600, 116, 927, 2515, 2601, 1001, 2819, 2514, 2717, 2646, 2743, 432, 3363, 3291, 2543, 519, 577, 806, 259, 264, 2312, 1613, 3237, 2905, 3261, 262, 409, 748, 1168, 166, 569, 726, 3213, 2043, 2519, 2979, 3566, 1964, 1745, 3316, 1409, 39, 1019, 2925, 3442, 980, 2557, 2721, 1628, 40, 98, 1991, 2493, 2741, 2616, 307, 3663, 2630, 2121, 2679, 34, 411, 32

In [45]:
course_name = "Ultimate Investment Banking Course"
def recommend_courses(course_name):
    movie_index = df_cleaned[df_cleaned["course_title"]==course_name].index[0]
    similar_indices = df_cleaned.loc[movie_index,"Similarity Indices"]
    top_5_movie_indices = similar_indices[0:5]
    df_top_5_movies = df_cleaned.loc[top_5_movie_indices,"course_title"].values
    return list(df_top_5_movies)
recommend_courses(course_name)

['The Complete Investment Banking Course 2017',
 'Advanced Accounting for Investment Banking',
 'The Ultimate jQuery Course',
 'The Ultimate Web Development Course',
 'Financial Accounting - The Ultimate Beginner Course']

In [46]:
course_name = "Ultimate Investment Banking Course"
def recommend_courses_1(course_name):
    movie_index = df_cleaned[df_cleaned["course_title"]==course_name].index[0]
    similar_indices = df_cleaned.loc[movie_index,"Similarity Indices"]
    top_5_movie_indices = similar_indices[0:5]
    df_top_5_movies = df_cleaned.loc[top_5_movie_indices,:]
    return df_top_5_movies
recommend_courses_1(course_name)

course_id                                         course_title  \
39       965832          The Complete Investment Banking Course 2017   
242      298558           Advanced Accounting for Investment Banking   
3479     633606                           The Ultimate jQuery Course   
2719      30240                  The Ultimate Web Development Course   
659     1136912  Financial Accounting - The Ultimate Beginner Course   

                                                                                     url  \
39                    https://www.udemy.com/the-complete-investment-banking-course-2016/   
242                    https://www.udemy.com/advanced-accounting-for-investment-banking/   
3479                                    https://www.udemy.com/essential-jquery-training/   
2719  https://www.udemy.com/build-an-instant-update-database-interface-with-jquery-ajax/   
659             https://www.udemy.com/financial-accounting-the-ultimate-beginner-course/   

      is_paid  price  num_subscribers  num_reviews  num_lectures  \
39       True    195             8575          809           110   
242      True     50             1260           80            38   
3479     True     20             1098           15            54   
2719     True     50             9881          329           136   
659      True    100                9            2           101   

                   level content_duration  ...           subject   profit  \
39            All Levels        5.5 hours  ...  Business Finance  1672125   
242   Intermediate Level          4 hours  ...  Business Finance    63000   
3479          All Levels        2.5 hours  ...   Web Development    21960   
2719          All Levels         12 hours  ...   Web Development   494050   
659       Beginner Level         10 hours  ...  Business Finance      900   

      published_date published_time  year  month  day  \
39        2016-10-10      16:16:26Z  2016     10   10   
242       2014-10-01      18:51:06Z  2014     10    1   
3479      2015-11-13      19:37:48Z  2015     11   13   
2719      2013-08-25      16:16:52Z  2013      8   25   
659       2017-04-06      00:39:12Z  2017      4    6   

                     course_title_cleaned  \
39         complet invest bank cours 2017   
242            advanc account invest bank   
3479                   ultim jqueri cours   
2719              ultim web develop cours   
659   financi account  ultim beginn cours   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Similarity Indices  \
39                                                        [0, 242, 1185, 26, 40, 419, 2981, 457, 1584, 420, 1365, 87, 229, 724, 140, 139, 335, 3326, 2515, 2601, 3279, 3112, 2819, 2514, 2717, 2646, 2743, 3363, 172, 3291, 380, 452, 2543, 806, 264, 2723, 173, 3237, 254, 2905, 530, 364, 1643, 3261, 1006, 417, 3213, 466, 3019, 2043, 2519, 2979, 3566, 1964, 1745, 3316, 446, 2925, 3327, 992, 2557, 3513, 441, 1628, 127, 2724, 271, 538, 567, 892, 1991, 2645, 73, 2493, 1152, 661, 2741, 2616, 3663, 539, 2630, 1001, 2679, 2491, 3, 34, 773, 775, 3231, 365, 105, 3146, 830, 2843, 5, 3396, 2746, 352, 497, 338, ...]   
242                                                                          [0, 39, 419, 530, 935, 271, 441, 1148, 420, 166, 497, 229, 724, 139, 2517, 335, 26, 2937, 634, 172, 1258, 173, 364, 629, 1006, 466, 304, 156, 2814, 939, 446, 476, 1146, 738, 3189, 992, 341, 127, 199, 538, 567, 892, 2645, 73, 2674, 1152, 