In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import cv2
from tqdm import *
from sklearn.metrics import *

In [2]:
train_images = []
train_labels = []

covid_19 = "C:\\Users\\amith\\Documents\\Datasets\\7 - COVID-19 Detection from CT Scans using ResNet, DenseNet, and VGG Mode\\train\\COVID-19\\"
non_covid_19 = "C:\\Users\\amith\\Documents\\Datasets\\7 - COVID-19 Detection from CT Scans using ResNet, DenseNet, and VGG Mode\\train\\Non-COVID-19\\"

for i in tqdm(os.listdir(covid_19),desc="Training of COVID-19 images"):
    file_name = covid_19 + i
    img = cv2.imread(file_name)
    img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img_resized = cv2.resize(src=img_grey,dsize=(64,64))
    img_reshaped = img_resized / 255.0
    img_reshaped = img_reshaped.reshape((64,64,1))
    train_images.append(img_reshaped)
    train_labels.append(1)

for i in tqdm(os.listdir(non_covid_19),desc="Training of Non-COVID-19 images"):
    file_name = non_covid_19 + i
    img = cv2.imread(file_name)
    img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img_resized = cv2.resize(src=img_grey,dsize=(64,64))
    img_reshaped = img_resized / 255.0
    img_reshaped = img_reshaped.reshape((64,64,1))
    train_images.append(img_reshaped)
    train_labels.append(0)

train_images = np.array(train_images)
train_labels = np.array(train_labels)

Training of Non-COVID-19 images: 100%|██████████| 604/604 [00:02<00:00, 254.67it/s]


In [3]:
val_images = []
val_labels = []

covid_19 = "C:\\Users\\amith\\Documents\\Datasets\\7 - COVID-19 Detection from CT Scans using ResNet, DenseNet, and VGG Mode\\val\\COVID-19\\"
non_covid_19 = "C:\\Users\\amith\\Documents\\Datasets\\7 - COVID-19 Detection from CT Scans using ResNet, DenseNet, and VGG Mode\\val\\Non-COVID-19\\"

for i in tqdm(os.listdir(covid_19),desc="Validation of COVID-19 images"):
    file_name = covid_19 + i
    img = cv2.imread(file_name)
    img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img_resized = cv2.resize(src=img_grey,dsize=(64,64))
    img_reshaped = img_resized / 255.0
    img_reshaped = img_reshaped.reshape((64,64,1))
    val_images.append(img_reshaped)
    val_labels.append(1)

for i in tqdm(os.listdir(non_covid_19),desc="Validation of Non-COVID-19 images"):
    file_name = non_covid_19 + i
    img = cv2.imread(file_name)
    img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img_resized = cv2.resize(src=img_grey,dsize=(64,64))
    img_reshaped = img_resized / 255.0
    img_reshaped = img_reshaped.reshape((64,64,1))
    val_images.append(img_reshaped)
    val_labels.append(0)

val_images = np.array(val_images)
val_labels = np.array(val_labels)

Validation of Non-COVID-19 images: 100%|██████████| 150/150 [00:00<00:00, 303.71it/s]


In [4]:
test_images = []
test_labels = []

covid_19 = "C:\\Users\\amith\\Documents\\Datasets\\7 - COVID-19 Detection from CT Scans using ResNet, DenseNet, and VGG Mode\\test\\COVID-19\\"
non_covid_19 = "C:\\Users\\amith\\Documents\\Datasets\\7 - COVID-19 Detection from CT Scans using ResNet, DenseNet, and VGG Mode\\test\\Non-COVID-19\\"

for i in tqdm(os.listdir(covid_19),desc="Testing of COVID-19 images"):
    file_name = covid_19 + i
    img = cv2.imread(file_name)
    img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img_resized = cv2.resize(src=img_grey,dsize=(64,64))
    img_reshaped = img_resized / 255.0
    img_reshaped = img_reshaped.reshape((64,64,1))
    test_images.append(img_reshaped)
    test_labels.append(1)

for i in tqdm(os.listdir(non_covid_19),desc="Testing of Non-COVID-19 images"):
    file_name = non_covid_19 + i
    img = cv2.imread(file_name)
    img_grey = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img_resized = cv2.resize(src=img_grey,dsize=(64,64))
    img_reshaped = img_resized / 255.0
    img_reshaped = img_reshaped.reshape((64,64,1))
    test_images.append(img_reshaped)
    test_labels.append(0)

test_images = np.array(test_images)
test_labels = np.array(test_labels)

Testing of Non-COVID-19 images: 100%|██████████| 190/190 [00:00<00:00, 395.54it/s]


In [5]:
model = tf.keras.models.Sequential(layers=[
    tf.keras.layers.Conv2D(filters=4,kernel_size=(3,3),activation="relu",input_shape=(64,64,1)),
    tf.keras.layers.Conv2D(filters=8,kernel_size=(3,3),activation="relu"),
    tf.keras.layers.Conv2D(filters=16,kernel_size=(3,3),activation="relu"),
    tf.keras.layers.Conv2D(filters=32,kernel_size=(3,3),activation="relu"),
    
    tf.keras.layers.Flatten(),
    
    tf.keras.layers.Dense(units=32,activation="relu"),
    tf.keras.layers.Dense(units=1,activation="softmax")
])

In [6]:
model.compile(optimizer=tf.keras.optimizers.Adam(),loss=tf.keras.losses.binary_crossentropy,metrics=["accuracy"])

In [7]:
model.fit(x=train_images,y=train_labels,batch_size=32,epochs=10,verbose=1,callbacks=tf.keras.callbacks.EarlyStopping(patience=1),validation_data=(val_images,val_labels),shuffle=True)

Epoch 1/10
169/169 [==============================] - 7s 32ms/step - loss: 0.1830 - accuracy: 0.8881 - val_loss: 0.1518 - val_accuracy: 0.8889
Epoch 2/10
169/169 [==============================] - 5s 31ms/step - loss: 0.0252 - accuracy: 0.8881 - val_loss: 0.2138 - val_accuracy: 0.8889


In [8]:
model.evaluate(x=test_images,y=test_labels)

53/53 [==============================] - 1s 10ms/step - loss: 0.4309 - accuracy: 0.8876


[0.430940717458725, 0.8875739574432373]

In [9]:
pred_labels = model.predict(x=test_images)
pred_labels

53/53 [==============================] - 1s 11ms/step


array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [10]:
acc = np.round(f1_score(y_true=test_labels,y_pred=pred_labels) * 100,2)
acc

94.04

In [11]:
tf.keras.models.save_model(model=model,filepath="C:\\Users\\amith\\Documents\\GitHub\\udemy\\7 - COVID-19 Detection from CT Scans using ResNet, DenseNet, and VGG Mode\\app\\model.h5")

C:\Users\amith\AppData\Local\Temp\ipykernel_83576\1601814802.py:1: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  tf.keras.models.save_model(model=model,filepath="C:\\Users\\amith\\Documents\\GitHub\\udemy\\7 - COVID-19 Detection from CT Scans using ResNet, DenseNet, and VGG Mode\\app\\model.h5")


In [12]:
test_images[0]

array([[[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       ...,

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]])

In [13]:
model.predict(x=test_images)

53/53 [==============================] - 0s 9ms/step


array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [19]:
model.predict(x=test_images[0].reshape(1,64,64,1))[0][0]

1/1 [==============================] - 0s 29ms/step


1.0